theme: jekyll-theme-cayman
title: Materials Project Workshop 2020
description: |
             July 28th through July 30th in Berkeley, CA
             <br><strong>Instructors</strong>:
             Samuel Blau, John Dagdelen, Alex Ganose, Matthew Horton, Tingzheng Hou, Patrick Huck, Jimmy Shen, Eric Sivonxay, Rebecca Stern, and Donny Winston
             <br><strong>Helpers</strong>:  Jordan Burns, Jianli Cheng, Shyam Dwaraknath, Alex Epstein, Ryan Kingsbury, Ann Rutt, and Martin Siron
