theme: jekyll-theme-cayman
title: Materials Project Workshop 2018
description: |
             August 8-10 in Berkeley, CA
             **Instructors**: John Dagdelen, Shyam Dwaraknath, Matthew Horton, Patrick Huck, Joseph Montoya, Donny Winston
