theme: jekyll-theme-cayman
title: Materials Project Workshop 2018
description: |
             August 8-10 in Berkeley, CA
             <br><strong>Instructors</strong>: John Dagdelen, Shyam Dwaraknath, Matthew Horton, Patrick Huck, Joseph Montoya, Donny Winston
