theme: jekyll-theme-cayman
title: Materials Project Workshop 2019
description: |
             July 31st through August 2nd in Berkeley, CA
             <br><strong>Instructors</strong>:
             John Dagdelen, Shyam Dwaraknath, Alexander Dunn, Alex Ganose, Matthew Horton, Patrick Huck, Donny Winston
             <br><strong>Helpers</strong>: Samuel Blau, David Mrdjenovich, Rachel Woods-Robinson
