name: r2d
channels:
  - conda-forge
  - matsci
dependencies:
  - python
  - numpy
  - pip
  - graphviz>=0.11.1
  - RISE
  - enumlib
  - pythreejs>=2.0.2
  - jupyter>=1.0.0
  - jupyter-server-proxy
  - pandas==0.23.4
  - matplotlib
  - pymatgen>=2019.3.27
  - ruamel.yaml>=0.15.94
  - pymongo>=3.8.0
  - monty>=2.0.4
  - tabulate>=0.8.3
  - flask>=1.0.2
  - flask-paginate>=0.5.1
  - gunicorn>=19.9.0
  - tqdm>=4.31.1
  - dash>=1.0.2
  - docutils<0.15,>=0.10
  - redis>=2.10.6
  - Flask-Caching>=1.3.3
  - gevent>=1.4.0
  - raven>=6.9.0
  - mongomock>=3.14.0
  - networkx>=2.0
  - scikit-learn>=0.20.2
  - toml>=0.10.0
  - fuzzywuzzy[speedup]>=0.17.0
  - bibtexparser>=1.1.0
  - pybtex>=0.22.2
  - latexcodec>=1.0.7
  - bravado[fido]>=10.4.1
  - service_identity>=18.1.0
  - plotly>=3.10.0
  - typing_extensions>=3.7.4
  - msgpack-python>=0.5.6
  - crochet>=1.10.0
  - Twisted>=19.2.1
  - jsonpointer>=2.0
  - rfc3987>=1.3.8
  - strict-rfc3339>=0.7
  - webcolors>=1.9.1
  - wrapt>=1.11.2
  - zope.interface>=4.6.0
  - constantly>=15.1.0
  - incremental>=17.5.0
  - Automat>=0.7.0
  - hyperlink>=19.0.0
  - PyHamcrest>=1.9.0
  - pip:
      - fido>=4.2.2
      - yelp_encodings>=0.1.3
      - yelp_bytes>=0.3.0
      - nbzip
      - atomate
      - maggma
      - matminer>=0.5.0
      - dash-auth>=1.3.2
      - dash-katex>=0.0.1
      - dash-dangerously-set-inner-html>=0.0.2
      - archieml>=0.3.4
      - robocrys>=0.1.3
      - habanero>=0.6.2
      - fireworks @ git+https://github.com/tschaume/fireworks#egg=fireworks
      - crystal-toolkit @ git+https://github.com/materialsproject/crystaltoolkit@43696099462f4b5566c81935078212f7db580ae1#egg=crystal-toolkit


