site_name: The Materials Project Workshop
site_description: Lessons for the Materials Project Workshop
copyright: Built by The Materials Project
docs_dir: workshop

theme:
  name: 'material'

nav:
  - Home: index.md
  - Lessons:
    - primer/01_basic_python/1 - Introduction and Jupyter Use.ipynb
    - primer/01_basic_python/2 - Variables and built-in functions.ipynb
    - primer/01_basic_python/3 - Lists.ipynb
    - primer/01_basic_python/4 - For loops.ipynb

site_url: https://workshop.materialsproject.org/
repo_url: https://github.com/materialsproject/workshop/

markdown_extensions:
  - admonition
  - codehilite
  - attr_list
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - toc:
      permalink: true

plugins:
  - search
  - minify
  - mknotebooks
