name: r2d
channels:
  - conda-forge
  - matsci
dependencies:
  - python>=3.7
  - numpy
  - pip
  - pymatgen
  - plotly
  - typing_extensions
  - pip:
      - nbzip
      - nbgitpuller
      - atomate>=0.9.5
      - maggma>=0.22.0
      - matminer>=0.6.3
      - robocrys>=0.2.4
      - crystal-toolkit>=2020.6.4
      - mpcontribs-client>=3.2.0
      - automatminer
