name: release

on:
  release:
    types: [published]

jobs:
  deploy:
    services:
      local_mongodb:
        image: mongo:4.0
        ports:
          - 27017:27017

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: goanpeca/setup-miniconda@v1
      with:
        activate-environment: anaconda-client-env
        environment-file: binder/environment.yml
        python-version: 3.8
        auto-activate-base: false

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-docs.txt
        pip install -e .

    - name: Build
      run: mkdocs build

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./site